### ISSUE TITLE
Getting acquainted with AXIOM Beta

### ISSUE THREAD

**Issue by maltefiala** [apertus-open-source-cinema/axiom-beta-rest-interface#2]
> Get acquainted with AXIOM beta, since my task doesn't require hardware much, so I would be using virtualisation tech and control daemon, currently Andrej is working on it, so I hope I will be getting my hands on with AXIOM development environment during this period.

**Comment by maltefiala** [comment]
https://wiki.apertus.org/index.php/AXIOM_Beta/AXIOM_Beta_Software

**Comment by anuditverma** [comment]
I am now familiar with the interface and how to run commands on AXIOM beta. Since I would be working locally more for a while now, I would keep trying my hands on my local setup.
